### PR TITLE
Java bindings + example

### PR DESCRIPTION
**Pull request by andreivasiliu2211**

### CODE REVIEW

**Comment by andreivasiliu2211** [comment]
This pull requests has the source files for the bindings, without the CMakelist.

**Comment by arfoll** [comment]
I'm confused so tinyB is no longer using SWIG to generate the java apis?

**Comment by petreeftime** [comment]
Unfortunately SWIG does not understand smart pointers or vectors/lists properly and is difficult to coax into working nicely with them. The library will be relatively limited in size, so we don't expect to have scalability issues with manual bindings.

**Comment by arfoll** [comment]
Fair enough ;-)

**Pull request merged**
