### PR TITLE
Adding support for setting discovery filters

### PR DESCRIPTION
**Pull request by vkolotov**
This PR is to merge @impala454's work (https://github.com/impala454/tinyb) to add support for setting discovery filters and to close https://github.com/intel-iot-devkit/tinyb/issues/80 issue.

I'm not a big expert in c++, it was a bit hard for me to properly merge you stuff @impala454 for dbus-codegen (https://github.com/intel-iot-devkit/tinyb/issues/101). I just only copied what I needed to implement setting discovery filters.

@petreeftime could you please review my changes and merge to the upstream?

PS. I have not tested c++ code directly, but I did some tests for java, this probably mean that c++ part works as well.

Signed-off-by: Vlad Kolotov <vkolotov@gmail.com>

### CODE REVIEW

**Comment by vkolotov** [comment]
This PR also should address that issue as well: https://github.com/intel-iot-devkit/tinyb/issues/98

**Comment by vkolotov** [comment]
@petreeftime @impala454 Looks like have managed to merge/implement SetDiscoveryFilter for both c++ and java. 

@petreeftime work is done, could you please merge it to the upstream?

**Comment by impala454** [comment]
Awesome, again sorry I fell off on this work, I was stoked to work on it but projects at work went another direction.  It may come back next year though. @petreeftime thanks for incorporating some of my stuff.

**Comment by petreeftime** [comment]
Looks good.

**Pull request merged**
