### PR TITLE
Fixed java typo and added removeDevices() in BluetoothAdapter class

### PR DESCRIPTION
**Pull request by lsimedia**
Java_tinyb_BluetoothDevice_getTXPower() should be
Java_tinyb_BluetoothDevice_getTxPower()

### CODE REVIEW

**Comment by petreeftime** [comment]
Please sign-off  on your commit.

**Comment by lsimedia** [comment]
Hi petreeftime, I sign-off my second commit...

**Comment by lsimedia** [comment]
I'm a bit confused with the pull request process, I tried to create a second pull request with the new removeDevices() method, but the commits are merged with this one...
I think I must close the pull request before adding  a new one.
Sorry for that... will do next time...

**Comment by sbodmer** [comment]
Added startNearbyDiscovery() and stopNearbyDiscovery() in java BluetoothManagert class to be notified when a new device is discovered.

**Comment by petreeftime** [comment]
Could you please make the commit titles slightly more verbose or squash them (make sure there aren't any duplicates) and get rid of the merge commit? Thanks.

**Comment by lsimedia** [comment]
Ok, I will try again in another pull request.

**Pull request closed without merging**
